data:
  images_dir: "data/images"
  ann_dir: "data/annotations"
  masks_dir: "data/masks"
  input_size: 320

train:
  epochs: 30
  batch_size: 8
  lr: 1e-4
  weight_decay: 5e-4

model:
  n_classes: 5
  base_ch: 32

loss:
  use_ce: true
  use_ssim: false
  ssim_lambda: 0.5
  edge_lambda: 0.1
